# Generated by Django 3.2.7 on 2021-10-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobCompanyName', models.CharField(max_length=300)),
                ('JobPositionName', models.CharField(max_length=300)),
                ('JobStart', models.DateField()),
                ('JobEnd', models.DateField()),
                ('JobDescription', models.CharField(max_length=5000)),
            ],
        ),
    ]
