# Generated by Django 3.2.7 on 2021-10-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_resumeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResumeTitle', models.CharField(max_length=200)),
            ],
        ),
    ]
