# Generated by Django 3.2.7 on 2021-11-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211106_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='postTitle',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
