# Generated by Django 3.2.7 on 2021-11-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_postitem_posttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeitem',
            name='JobDetail0',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='JobDetail1',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='JobDetail2',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='JobDetail3',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='JobDetail4',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='JobDetail5',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='JobDetail6',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='JobDetail7',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='JobDetail8',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='JobDetail9',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='postTitle',
            field=models.CharField(max_length=300),
        ),
    ]
