# Generated by Django 3.2.7 on 2021-12-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='ClientLogo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
