# Generated by Django 3.2.7 on 2021-12-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_clients_clientlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='ClientLogo',
            field=models.ImageField(blank=True, default='default', upload_to=''),
            preserve_default=False,
        ),
    ]
